FROM golang:1.22.7-alpine

RUN apk add --no-cache gcc musl-dev

WORKDIR /go/src/consent-validator

COPY go.mod ./
COPY consent-validator.go ./

RUN CGO_ENABLED=1 go build -buildmode=plugin -o /go/plugin/consent-validator.so .

CMD ["cp", "/go/plugin/consent-validator.so", "/go/output/consent-validator.so"]
