version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-auth
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ginga_net

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - ginga_net

volumes:
  redis_data:

networks:
  ginga_net:
    external: true
    name: ginga_net
